# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    paths:
      - '!.cirrus.yml'
      - 'rust/**'
  pull_request:
    paths:
      - '!.cirrus.yml'
  
jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        node-version: [14,15,16,17,18,19,20]
        os: [ubuntu-latest,macos-latest,windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | # https://github.com/nodejs/node-gyp/blob/main/docs/Updating-npm-bundled-node-gyp.md
        npm -v
        npm explore npm/node_modules/@npmcli/run-script -g -- npm_config_global=false npm install node-gyp@latest
      if: matrix.node-version == '15' && runner.os == 'MacOS'
    - run: |
        npm config set msvs_version 2017
        npm -v
        where node
        cd $(where node)
        npm install node-gyp@latest
      # npm install --global node-gyp@latest
      # npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
      if: matrix.node-version == '14' || matrix.node-version == '15' && runner.os == 'Windows'
    - run: ./scripts/ci/test.sh
